name: Developement Pipeline

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm ci  

      - name: Run lint
        run: npm run lint  

      - name: Run tests
        run: npm run test  

      - name: Build application
        run: npm run build 

      - name: List build directory contents
        run: ls -la build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Remove old files
        run: git rm -rf ./*  # Clear old files in the main branch

      - name: Copy build files
        run: cp -R ./build/* ./  # Copy new build files to the root

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Deploying to GitHub Pages" || echo "No changes to commit"

      - name: Push changes to main branch
        run: git push origin mai